language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mthanasides/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true mthanasides/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-385538042411"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"