language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build mthanasides/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true mthanasides/docker-react npm run test